### ISSUE TITLE
spawn point(s)

### ISSUE THREAD

**Issue by harleyBTP** [Five999/bugs#1]
### Describe the Bug

Heath-row station within MPS will need to be removed as a spawn option via coding (i believe).

### Expected Behavior

to ot be able to spawn here as it isn't anymore a working station. 

### To Reproduce

remove coding so it isnt a spawn point. 

### Screenshots or crash reports

![image](https://github.com/Five999/bugs/assets/143006998/cf8c3630-27d8-4ebe-870a-518ba52c399b)

**Comment by colossalengineer** [comment]
It has been removed in Dev we are just waiting to push it to main

**Comment by harleyBTP** [comment]
Ok mate all good
