### ISSUE TITLE
LT and Moderator Hide

### ISSUE THREAD

**Issue by WolfRanger88** [Five999/bugs#2]
### What division were you running as?

Moderator

### Describe the Bug

Hide player in wheel menu does not hide blip or name tag from other players

### Expected Behavior

Name tag and blip expected to be hidden

### To Reproduce

Use radial menu to hide and ask player to confirm

**Comment by jxckUK** [comment]
Are you sure this doesn't hide your blip? I've tested this, think its likely just nametags.

**Comment by colossalengineer** [comment]
> Are you sure this doesn't hide your blip? I've tested this, think its likely just nametags.

Can confirm that
