### ISSUE TITLE
LFB 32m Ladder

### ISSUE THREAD

**Issue by james-peth** [Five999/bugs#9]
### Describe the Bug

Driving about in the ladder and I had reports of people not being able to see the vehicle itself but being able to see the ladder. If you are also in the ladder, you cant hear people outside the ladder/inside the ladder.

### Expected Behavior

Fix the ladder.

### To Reproduce

All that happened was once spawned in at Davies Fire Station people said they couldn't see the vehicle itself. They had to type in chat to get my attention since they couldn't hear me/ I couldn't hear them in the ladder.

**Comment by colossalengineer** [comment]
Fixed In Dev
